version: '3.8'

services:
  app:
    image: leonardobolzan/infnet-hello-world:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=cache_redis
    ports:
      - "80:80"
    deploy:
      replicas: 4
    networks:
      - overlay-net

networks:
  overlay-net:
    driver: overlay
    attachable: true