name: Deploy App no Docker Swarm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir e enviar a imagem para o Docker Hub
        run: |
          docker build -t leonardobolzan/infnet-hello-world:latest .
          docker push leonardobolzan/infnet-hello-world:latest

      - name: Deploy no Docker Swarm
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SWARM_MANAGER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker service update --image leonardobolzan/infnet-hello-world:latest infnet_app